version: '3'
services:
  api:
    container_name: api
    build: .
    entrypoint: python main.py
    env_file:
      - .env
    ports:
      - '5000:5000'
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"