version: '3'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ${PWD}:/app:rw
  redis:
    image: redis
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"